### import pandas as pd
from sklearn.linear_model import LogisticRegression
import numpy as np

In [20]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
import numpy as np

In [14]:
df=pd.read_csv("pass_fail.csv")
df.head(5)

   Hours Result
0      1   Fail
1      2   Fail
2      3   Fail
3      4   Pass
4      5   Pass

In [15]:
X=df[['Hours']]
y=df['Result']

In [16]:
model=LogisticRegression()

In [17]:
model.fit(X,y)

LogisticRegression()

In [18]:
pred_35=model.predict([[3.5]])
print('Predicted result for 3.5 hours:', pred_35[0])

Predicted result for 3.5 hours: Pass

C:\Users\angkel\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [19]:
hours_study=float(input('Number of hours studied'))
pred_value=model.predict([[hours_study]])
print(f'After {hours_study} hours study you are likely to {pred_value[0]}')

Number of hours studied 1.2

After 1.2 hours study you are likely to Fail

C:\Users\angkel\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [46]:
#Step 1: prepare library

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [47]:
#Step 2: collect data

df=pd.read_csv("customer_purchase.csv")
df.head(5)

   Age  Salary Purchased
0   22   25000        No
1   25   30000        No
2   30   40000       Yes
3   35   50000       Yes
4   40   60000       Yes

In [48]:
# Step 3: defining & labelling data

le=LabelEncoder()

df['Purchased']=le.fit_transform(df['Purchased'])
X=df[['Age','Salary']]
y=df['Purchased']

In [49]:
df

   Age  Salary  Purchased
0   22   25000          0
1   25   30000          0
2   30   40000          1
3   35   50000          1
4   40   60000          1

In [50]:
model=LogisticRegression()

In [51]:
model.fit(X,y)

LogisticRegression()

In [52]:
new_cust_age=int(input('Enter your age: '))
new_cust_sal=int(input('Enter your salary: '))
profile=[[new_cust_age, new_cust_sal]]
prediction=model.predict(profile)
if (prediction):
    print(f'{profile[0][1]} Purchasing')
else:
    print('Not Purchasing')

Enter your age:  33
Enter your salary:  33000

Not Purchasing

C:\Users\angkel\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

## Exercise for Logistic Regression - Email Spam or Not dataset

In [113]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import CountVectorizer

In [114]:
df=pd.read_csv("spam_dataset.csv")
df.head(5)

                                     message_content  is_spam
0  Hello Lonnie,\n\nJust wanted to touch base reg...        0
1  Congratulations, you've won a prize! Call us n...        1
2  You have been pre-approved for a credit card w...        1
3  Limited time offer, act now! Only a few spots ...        1
4  Your loan has been approved! Transfer funds to...        1

In [115]:
num_rows = len(df)
print(f"Number of rows: {num_rows}")

Number of rows: 1000

In [116]:
print('Number of Missing Values are:',df.isnull().sum())

Number of Missing Values are: message_content    0
is_spam            0
dtype: int64

In [128]:
X=df['message_content']
y=df['is_spam']

cv=CountVectorizer()
X_cv=cv.fit_transform(X)

In [129]:
model=LogisticRegression()

In [131]:
model.fit(X_cv,y)

LogisticRegression()

In [140]:
sample=str(input('Message Received: '))
prediction=model.predict(cv.transform(sample))
if(prediction.all()):
    print('Not Spam')
else:
    print('Spam')

Message Received:  Limited time offer, act now!

ValueError: Iterable over raw text documents expected, string object received.