# We are going to write one Multi Label Classification example using TensorFlow here.

In [194]:
import tensorflow as tf
import pandas as pd
from sklearn.preprocessing import MultiLabelBinarizer
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [195]:
data = {
    "Overview":
    [
        # Original Samples
        # "A Hero Saves the city from destruction",
        # "A girl and boy become friends during war",
        # "A funny story of collegues during office meet",
        # "One scary nights in a deserted place",

        # Improvised Samples (Multi-Label focus)
        "A detective chases a supernatural killer through a gritty futuristic metropolis",
        "A high school prodigy accidentally invents a time machine and chaos ensues",
        "Two estranged sisters must fight a shadowy government conspiracy using ancient martial arts",
        "An eccentric chef enters a high-stakes cooking competition with hilarious and disastrous results",
        "A heartbreaking tale of a family separated during a global pandemic, battling isolation and hope",
        "A group of scientists uncovers a monstrous organism deep in the Antarctic ice",
        "A washed-up boxer trains for one last championship fight while juggling fatherhood and debt",
        "A medieval knight wakes up in the modern world and tries to navigate traffic and technology",
    ],
    "genres":
    [
        # Original Labels
        # ['Action', 'Adventure'],
        # ['Romance', 'Drama'],
        # ['Comedy'],
        # ['Horror'],

        # Improvised Labels
        ['Sci-Fi', 'Thriller', 'Crime'],
        ['Sci-Fi', 'Comedy', 'Adventure'],
        ['Action', 'Thriller', 'Drama'],
        ['Comedy', 'Family'],
        ['Drama', 'Romance'],
        ['Horror', 'Sci-Fi', 'Mystery'],
        ['Sport', 'Drama'],
        ['Fantasy', 'Comedy', 'Adventure'],
    ]
}

In [196]:
df = pd.DataFrame(data)
df

,Overview,genres
0,A detective chases a supernatural killer throu...,"[Sci-Fi, Thriller, Crime]"
1,A high school prodigy accidentally invents a t...,"[Sci-Fi, Comedy, Adventure]"
2,Two estranged sisters must fight a shadowy gov...,"[Action, Thriller, Drama]"
3,An eccentric chef enters a high-stakes cooking...,"[Comedy, Family]"
4,A heartbreaking tale of a family separated dur...,"[Drama, Romance]"
5,A group of scientists uncovers a monstrous org...,"[Horror, Sci-Fi, Mystery]"
6,A washed-up boxer trains for one last champion...,"[Sport, Drama]"
7,A medieval knight wakes up in the modern world...,"[Fantasy, Comedy, Adventure]"

In [197]:
mlb = MultiLabelBinarizer()
y = mlb.fit_transform(df['genres'])
y

array([[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1],
       [0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]])

In [198]:
tokenizer = Tokenizer(num_words=5000, oov_token='<OOV>')
tokenizer.fit_on_texts(df['Overview'])
X = tokenizer.texts_to_sequences(df['Overview'])
X = pad_sequences(X, maxlen=20, padding='post', truncating='post')

In [199]:
model = tf.keras.Sequential(
    [
        tf.keras.layers.Embedding(input_dim=5000, output_dim=16, input_length=20),
        tf.keras.layers.GlobalAveragePooling1D(),
        tf.keras.layers.Dense(16, activation='relu'),
        tf.keras.layers.Dense(len(mlb.classes_), activation='sigmoid')
    ]
)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [200]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [201]:
model.fit(X, y, epochs=20)

Epoch 1/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.1250 - loss: 0.6929
Epoch 2/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.1250 - loss: 0.6918
Epoch 3/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.1250 - loss: 0.6908
Epoch 4/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.1250 - loss: 0.6899
Epoch 5/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.1250 - loss: 0.6890
Epoch 6/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.1250 - loss: 0.6880
Epoch 7/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.1250 - loss: 0.6870
Epoch 8/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.2500 - loss: 0.6860
Epoch 9/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.2500 - loss: 0.6849
Epoch 10/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.2500 - loss: 0.6838
Epoch 11/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.2500 - loss: 0.6827
Epoch 12/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.2500 - loss: 0.6816
Epoch 13/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.2500 - loss: 0.6804
Epoch 14/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.2500 - loss: 0.6793
Epoch 15/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.2500 - loss: 0.6781
Epoch 16/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.2500 - loss: 0.6768
Epoch 17/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.2500 - loss: 0.6755
Epoch 18/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.2500 - loss: 0.6742
Epoch 19/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.2500 - loss: 0.6729
Epoch 20/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.2500 - loss: 0.6715

In [202]:
#evaluate
loss, accuracy = model.evaluate(X, y)
print(f"Loss: {loss:.4f}")
print(f"Accuracy: {accuracy:.4f}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 204ms/step - accuracy: 0.3750 - loss: 0.6701
Loss: 0.6701
Accuracy: 0.3750

In [203]:
# predict on a new movie overview
new_movie_overview = ['A detective chases a supernatural killer through a gritty futuristic metropolis']
seq = tokenizer.texts_to_sequences(new_movie_overview)
seq = pad_sequences(seq, maxlen=20, padding='post', truncating='post')
prediction = model.predict(seq)
prediction_labels = [mlb.classes_[i] for i in range(len(mlb.classes_)) if prediction[0][i] > 0.5]
print(f"Predicted genres: {prediction_labels}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step
Predicted genres: ['Thriller']

In [204]:
data_2 = {
    "headline": [
        "Government launches new digital economy policy",
        "Star player wins championship after dramatic final",
        "Tech company releases AI-powered smartphone",
        "Stock market drops amid political tensions",
        "New environmental policy gains global support",
        "Space agency announces manned Mars mission"
    ],
    "topics": [
        ["Politics", "Economy", "Technology"],
        ["Sports"],
        ["Technology", "Business"],
        ["Economy", "Politics"],
        ["Environment", "Politics"],
        ["Science", "Technology"]
    ]
}

In [205]:
df_2 = pd.DataFrame(data_2)
df_2

,headline,topics
0,Government launches new digital economy policy,"[Politics, Economy, Technology]"
1,Star player wins championship after dramatic f...,[Sports]
2,Tech company releases AI-powered smartphone,"[Technology, Business]"
3,Stock market drops amid political tensions,"[Economy, Politics]"
4,New environmental policy gains global support,"[Environment, Politics]"
5,Space agency announces manned Mars mission,"[Science, Technology]"

In [207]:
mlb_2 = MultiLabelBinarizer()
y_2 = mlb_2.fit_transform(df_2['topics'])
y_2

array([[0, 1, 0, 1, 0, 0, 1],
       [0, 0, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 0, 1],
       [0, 1, 0, 1, 0, 0, 0],
       [0, 0, 1, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 1]])

In [208]:
tokenizer_2 = Tokenizer(num_words=5000, oov_token='<OOV>')
tokenizer_2.fit_on_texts(df_2['headline'])
X_2 = tokenizer_2.texts_to_sequences(df_2['headline'])
X_2 = pad_sequences(X_2, maxlen=20, padding='post', truncating='post')

In [209]:
model_2 = tf.keras.Sequential(
    [
        tf.keras.layers.Embedding(input_dim=5000, output_dim=16, input_length=20),
        tf.keras.layers.GlobalAveragePooling1D(),
        tf.keras.layers.Dense(16, activation='relu'),
        tf.keras.layers.Dense(len(mlb_2.classes_), activation='sigmoid')
    ]
)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [210]:
model_2.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [211]:
model_2.fit(X_2, y_2, epochs=20)

Epoch 1/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.1667 - loss: 0.6940
Epoch 2/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.0000e+00 - loss: 0.6922
Epoch 3/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.1667 - loss: 0.6908
Epoch 4/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.3333 - loss: 0.6895
Epoch 5/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.3333 - loss: 0.6884
Epoch 6/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step - accuracy: 0.3333 - loss: 0.6873
Epoch 7/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.3333 - loss: 0.6862
Epoch 8/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.3333 - loss: 0.6851
Epoch 9/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.3333 - loss: 0.6840
Epoch 10/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.3333 - loss: 0.6829
Epoch 11/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.3333 - loss: 0.6817
Epoch 12/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.3333 - loss: 0.6806
Epoch 13/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.3333 - loss: 0.6794
Epoch 14/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.3333 - loss: 0.6782
Epoch 15/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.3333 - loss: 0.6769
Epoch 16/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.3333 - loss: 0.6755
Epoch 17/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.3333 - loss: 0.6742
Epoch 18/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.3333 - loss: 0.6728
Epoch 19/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.3333 - loss: 0.6713
Epoch 20/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.3333 - loss: 0.6698

In [212]:
#evaluate
loss, accuracy = model_2.evaluate(X_2, y_2)
print(f"Loss: {loss:.4f}")
print(f"Accuracy: {accuracy:.4f}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 297ms/step - accuracy: 0.3333 - loss: 0.6683
Loss: 0.6683
Accuracy: 0.3333

In [213]:
# predict on a new headline
new_headline = ['Star player wins championship after dramatic final']
seq2 = tokenizer_2.texts_to_sequences(new_headline)
seq2 = pad_sequences(seq2, maxlen=20, padding='post', truncating='post')
prediction2 = model_2.predict(seq2)
prediction_labels_2 = [mlb_2.classes_[i] for i in range(len(mlb_2.classes_)) if prediction2[0][i] > 0.5]
print(f"Predicted topics: {prediction_labels_2}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step
Predicted topics: ['Economy', 'Science']