# Binary Classification: Step for Modelling


1.   Creating the model
2.   Compiling the model
3.   Define a loss function
4.   Setting up an optimizer
5.   Finding best learning size
6.   Creating evaluation metrics
7.   Fitting model
8.   Improve model

## Predict Heart Disease


*   Load Dataset
*   Split features and Test
*   Train Test Spil
*   Scale features

In [15]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [3]:
heart_df = pd.read_csv('/content/sample_data/heart.csv')
heart_df.head()

   age  sex  chol  trestbps  thalach  target
0   52    1   200       130      150       1
1   58    0   240       150      140       1
2   60    1   180       140      145       0
3   48    1   190       120      160       0
4   50    0   220       125      155       1

In [4]:
X = heart_df.drop('target', axis=1)
y = heart_df['target']

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [6]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [7]:
model = tf.keras.Sequential(
    [
        tf.keras.layers.Dense(16, activation='relu', input_shape=(X_train.shape[1],)),
        tf.keras.layers.Dense(8, activation='relu'),
        tf.keras.layers.Dense(1, activation='sigmoid')
    ]
)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [8]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [9]:
#Train Model
history_model = model.fit(X_train_scaled, y_train, epochs=100, batch_size=32, validation_data=(X_test_scaled, y_test))

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 4s 4s/step - accuracy: 0.5000 - loss: 0.7418 - val_accuracy: 0.5000 - val_loss: 0.8369
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 456ms/step - accuracy: 0.5000 - loss: 0.7381 - val_accuracy: 0.5000 - val_loss: 0.8275
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 254ms/step - accuracy: 0.5000 - loss: 0.7344 - val_accuracy: 0.5000 - val_loss: 0.8183
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 313ms/step - accuracy: 0.5000 - loss: 0.7307 - val_accuracy: 0.5000 - val_loss: 0.8093
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 322ms/step - accuracy: 0.5000 - loss: 0.7270 - val_accuracy: 0.5000 - val_loss: 0.8005
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 242ms/step - accuracy: 0.5000 - loss: 0.7234 - val_accuracy: 0.5000 - val_loss: 0.7920
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 267ms/step - accuracy: 0.5000 - loss: 0.7198 - val_accuracy: 0.5000 - val_loss: 0.7837
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 319ms/step - accuracy: 0.5000 - loss: 0.7163 - val_accuracy: 0.5000 - val_loss: 0.7759
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step - accuracy: 0.5000 - loss: 0.7128 - val_accuracy: 0.5000 - val_loss: 0.7684
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 200ms/step - accuracy: 0.5000 - loss: 0.7093 - val_accuracy: 0.5000 - val_loss: 0.7611
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 303ms/step - accuracy: 0.5000 - loss: 0.7059 - val_accuracy: 0.5000 - val_loss: 0.7539
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 218ms/step - accuracy: 0.5000 - loss: 0.7025 - val_accuracy: 0.5000 - val_loss: 0.7471
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.5000 - loss: 0.6991 - val_accuracy: 0.5000 - val_loss: 0.7403
Epoch 14/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.6250 - loss: 0.6958 - val_accuracy: 0.5000 - val_loss: 0.7338
Epoch 15/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.6250 - loss: 0.6924 - val_accuracy: 0.5000 - val_loss: 0.7274
Epoch 16/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step - accuracy: 0.6250 - loss: 0.6891 - val_accuracy: 0.5000 - val_loss: 0.7212
Epoch 17/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.6250 - loss: 0.6859 - val_accuracy: 0.5000 - val_loss: 0.7152
Epoch 18/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.6250 - loss: 0.6826 - val_accuracy: 0.5000 - val_loss: 0.7094
Epoch 19/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.6250 - loss: 0.6794 - val_accuracy: 0.5000 - val_loss: 0.7037
Epoch 20/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.6250 - loss: 0.6761 - val_accuracy: 0.5000 - val_loss: 0.6981
Epoch 21/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step - accuracy: 0.6250 - loss: 0.6728 - val_accuracy: 0.5000 - val_loss: 0.6926
Epoch 22/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.6250 - loss: 0.6694 - val_accuracy: 0.5000 - val_loss: 0.6873
Epoch 23/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.6250 - loss: 0.6661 - val_accuracy: 0.5000 - val_loss: 0.6820
Epoch 24/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - accuracy: 0.6250 - loss: 0.6627 - val_accuracy: 0.5000 - val_loss: 0.6769
Epoch 25/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step - accuracy: 0.6250 - loss: 0.6594 - val_accuracy: 0.5000 - val_loss: 0.6719
Epoch 26/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.6250 - loss: 0.6560 - val_accuracy: 0.5000 - val_loss: 0.6670
Epoch 27/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step - accuracy: 0.6250 - loss: 0.6527 - val_accuracy: 0.5000 - val_loss: 0.6622
Epoch 28/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.6250 - loss: 0.6494 - val_accuracy: 0.5000 - val_loss: 0.6575
Epoch 29/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.6250 - loss: 0.6462 - val_accuracy: 0.5000 - val_loss: 0.6529
Epoch 30/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.6250 - loss: 0.6430 - val_accuracy: 0.5000 - val_loss: 0.6483
Epoch 31/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - accuracy: 0.6250 - loss: 0.6397 - val_accuracy: 0.5000 - val_loss: 0.6439
Epoch 32/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - accuracy: 0.6250 - loss: 0.6365 - val_accuracy: 0.5000 - val_loss: 0.6389
Epoch 33/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.6250 - loss: 0.6333 - val_accuracy: 0.5000 - val_loss: 0.6340
Epoch 34/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.6250 - loss: 0.6301 - val_accuracy: 0.5000 - val_loss: 0.6292
Epoch 35/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.6250 - loss: 0.6268 - val_accuracy: 0.5000 - val_loss: 0.6244
Epoch 36/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.6250 - loss: 0.6237 - val_accuracy: 0.5000 - val_loss: 0.6197
Epoch 37/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - accuracy: 0.6250 - loss: 0.6205 - val_accuracy: 0.5000 - val_loss: 0.6151
Epoch 38/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.7500 - loss: 0.6174 - val_accuracy: 1.0000 - val_loss: 0.6106
Epoch 39/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step - accuracy: 0.7500 - loss: 0.6142 - val_accuracy: 1.0000 - val_loss: 0.6061
Epoch 40/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.7500 - loss: 0.6110 - val_accuracy: 1.0000 - val_loss: 0.6017
Epoch 41/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - accuracy: 0.7500 - loss: 0.6078 - val_accuracy: 1.0000 - val_loss: 0.5974
Epoch 42/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.7500 - loss: 0.6046 - val_accuracy: 1.0000 - val_loss: 0.5932
Epoch 43/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.7500 - loss: 0.6014 - val_accuracy: 1.0000 - val_loss: 0.5891
Epoch 44/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - accuracy: 0.7500 - loss: 0.5983 - val_accuracy: 1.0000 - val_loss: 0.5852
Epoch 45/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.7500 - loss: 0.5951 - val_accuracy: 1.0000 - val_loss: 0.5815
Epoch 46/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - accuracy: 0.7500 - loss: 0.5919 - val_accuracy: 1.0000 - val_loss: 0.5779
Epoch 47/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.7500 - loss: 0.5887 - val_accuracy: 1.0000 - val_loss: 0.5743
Epoch 48/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.7500 - loss: 0.5858 - val_accuracy: 1.0000 - val_loss: 0.5708
Epoch 49/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.7500 - loss: 0.5829 - val_accuracy: 1.0000 - val_loss: 0.5673
Epoch 50/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - accuracy: 0.7500 - loss: 0.5799 - val_accuracy: 1.0000 - val_loss: 0.5638
Epoch 51/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step - accuracy: 0.7500 - loss: 0.5769 - val_accuracy: 1.0000 - val_loss: 0.5604
Epoch 52/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.7500 - loss: 0.5739 - val_accuracy: 1.0000 - val_loss: 0.5569
Epoch 53/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - accuracy: 0.7500 - loss: 0.5709 - val_accuracy: 1.0000 - val_loss: 0.5535
Epoch 54/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.7500 - loss: 0.5678 - val_accuracy: 1.0000 - val_loss: 0.5502
Epoch 55/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.7500 - loss: 0.5648 - val_accuracy: 1.0000 - val_loss: 0.5469
Epoch 56/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.7500 - loss: 0.5618 - val_accuracy: 1.0000 - val_loss: 0.5437
Epoch 57/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 0.7500 - loss: 0.5588 - val_accuracy: 1.0000 - val_loss: 0.5406
Epoch 58/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.7500 - loss: 0.5556 - val_accuracy: 1.0000 - val_loss: 0.5376
Epoch 59/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - accuracy: 0.7500 - loss: 0.5525 - val_accuracy: 1.0000 - val_loss: 0.5345
Epoch 60/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - accuracy: 0.7500 - loss: 0.5494 - val_accuracy: 1.0000 - val_loss: 0.5314
Epoch 61/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.7500 - loss: 0.5463 - val_accuracy: 1.0000 - val_loss: 0.5284
Epoch 62/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.8750 - loss: 0.5432 - val_accuracy: 1.0000 - val_loss: 0.5253
Epoch 63/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step - accuracy: 0.8750 - loss: 0.5401 - val_accuracy: 1.0000 - val_loss: 0.5222
Epoch 64/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.8750 - loss: 0.5369 - val_accuracy: 1.0000 - val_loss: 0.5196
Epoch 65/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.8750 - loss: 0.5337 - val_accuracy: 1.0000 - val_loss: 0.5173
Epoch 66/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.8750 - loss: 0.5306 - val_accuracy: 1.0000 - val_loss: 0.5151
Epoch 67/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - accuracy: 0.8750 - loss: 0.5274 - val_accuracy: 1.0000 - val_loss: 0.5128
Epoch 68/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.8750 - loss: 0.5242 - val_accuracy: 1.0000 - val_loss: 0.5106
Epoch 69/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.8750 - loss: 0.5211 - val_accuracy: 1.0000 - val_loss: 0.5085
Epoch 70/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step - accuracy: 0.8750 - loss: 0.5179 - val_accuracy: 1.0000 - val_loss: 0.5063
Epoch 71/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.8750 - loss: 0.5147 - val_accuracy: 1.0000 - val_loss: 0.5042
Epoch 72/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.8750 - loss: 0.5115 - val_accuracy: 1.0000 - val_loss: 0.5021
Epoch 73/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.8750 - loss: 0.5082 - val_accuracy: 1.0000 - val_loss: 0.5000
Epoch 74/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.8750 - loss: 0.5049 - val_accuracy: 1.0000 - val_loss: 0.4979
Epoch 75/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - accuracy: 0.8750 - loss: 0.5014 - val_accuracy: 1.0000 - val_loss: 0.4957
Epoch 76/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.8750 - loss: 0.4978 - val_accuracy: 1.0000 - val_loss: 0.4934
Epoch 77/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.8750 - loss: 0.4942 - val_accuracy: 1.0000 - val_loss: 0.4912
Epoch 78/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - accuracy: 0.8750 - loss: 0.4906 - val_accuracy: 1.0000 - val_loss: 0.4888
Epoch 79/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.8750 - loss: 0.4869 - val_accuracy: 1.0000 - val_loss: 0.4865
Epoch 80/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step - accuracy: 0.8750 - loss: 0.4832 - val_accuracy: 1.0000 - val_loss: 0.4840
Epoch 81/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - accuracy: 0.8750 - loss: 0.4795 - val_accuracy: 1.0000 - val_loss: 0.4815
Epoch 82/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.8750 - loss: 0.4758 - val_accuracy: 1.0000 - val_loss: 0.4788
Epoch 83/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.8750 - loss: 0.4721 - val_accuracy: 1.0000 - val_loss: 0.4761
Epoch 84/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.8750 - loss: 0.4684 - val_accuracy: 1.0000 - val_loss: 0.4733
Epoch 85/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.8750 - loss: 0.4647 - val_accuracy: 1.0000 - val_loss: 0.4705
Epoch 86/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.8750 - loss: 0.4610 - val_accuracy: 1.0000 - val_loss: 0.4676
Epoch 87/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step - accuracy: 0.8750 - loss: 0.4573 - val_accuracy: 1.0000 - val_loss: 0.4647
Epoch 88/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.8750 - loss: 0.4536 - val_accuracy: 1.0000 - val_loss: 0.4619
Epoch 89/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.8750 - loss: 0.4499 - val_accuracy: 1.0000 - val_loss: 0.4592
Epoch 90/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 165ms/step - accuracy: 0.8750 - loss: 0.4462 - val_accuracy: 1.0000 - val_loss: 0.4564
Epoch 91/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 183ms/step - accuracy: 0.8750 - loss: 0.4425 - val_accuracy: 1.0000 - val_loss: 0.4537
Epoch 92/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 257ms/step - accuracy: 0.8750 - loss: 0.4388 - val_accuracy: 1.0000 - val_loss: 0.4510
Epoch 93/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step - accuracy: 1.0000 - loss: 0.4351 - val_accuracy: 1.0000 - val_loss: 0.4483
Epoch 94/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step - accuracy: 1.0000 - loss: 0.4314 - val_accuracy: 1.0000 - val_loss: 0.4456
Epoch 95/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 170ms/step - accuracy: 1.0000 - loss: 0.4276 - val_accuracy: 1.0000 - val_loss: 0.4430
Epoch 96/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 263ms/step - accuracy: 1.0000 - loss: 0.4239 - val_accuracy: 1.0000 - val_loss: 0.4404
Epoch 97/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step - accuracy: 1.0000 - loss: 0.4202 - val_accuracy: 1.0000 - val_loss: 0.4379
Epoch 98/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step - accuracy: 1.0000 - loss: 0.4165 - val_accuracy: 1.0000 - val_loss: 0.4354
Epoch 99/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 310ms/step - accuracy: 1.0000 - loss: 0.4128 - val_accuracy: 1.0000 - val_loss: 0.4330
Epoch 100/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 173ms/step - accuracy: 1.0000 - loss: 0.4091 - val_accuracy: 1.0000 - val_loss: 0.4305

In [10]:
# Evaluate the model
loss, accuracy = model.evaluate(X_test_scaled, y_test)
print(f'Test Loss: {loss:.4f}')
print(f'Test Accuracy: {accuracy:.4f}')

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 1.0000 - loss: 0.4305
Test Loss: 0.4305
Test Accuracy: 1.0000

## Example 2
- Bank Customer Exit Prediction
Based on given data using Neural network binary classifier find out is customer going to stay or leave stay : (Churn = 0) and leave (churn=1).
Predict the result for new data as well at end

In [35]:
bank_df = pd.read_csv('/content/sample_data/bank_churn.csv')
bank_df.head()

,CreditScore,Geography,Gender,Age,Balance,NumOfProducts,EstimatedSalary,Exited
0,600,France,Male,40,60000,1,50000,0
1,700,Spain,Female,45,70000,2,60000,0
2,800,Germany,Female,38,80000,1,70000,1
3,400,France,Male,30,30000,1,40000,1
4,550,Spain,Male,50,40000,2,42000,0

In [36]:
le = LabelEncoder()
bank_df['Gender'] = le.fit_transform(bank_df['Gender'])
bank_df = pd.get_dummies(bank_df, columns=['Geography'])

bank_df.head()

,CreditScore,Gender,Age,Balance,NumOfProducts,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,60000,1,50000,0,True,False,False
1,700,0,45,70000,2,60000,0,False,False,True
2,800,0,38,80000,1,70000,1,False,True,False
3,400,1,30,30000,1,40000,1,True,False,False
4,550,1,50,40000,2,42000,0,False,False,True

In [37]:
X_bank = bank_df.drop('Exited', axis=1)
y_bank = bank_df['Exited']

In [38]:
X_train_bank, X_test_bank, y_train_bank, y_test_bank = train_test_split(X_bank, y_bank, test_size=0.2, random_state=42)

In [39]:
scaler_bank = StandardScaler()
X_train_scaled_bank = scaler_bank.fit_transform(X_train_bank)
X_test_scaled_bank = scaler_bank.transform(X_test_bank)

In [40]:
#create model
model_bank = tf.keras.Sequential(
    [
        tf.keras.layers.Dense(16, activation='relu', input_shape=(X_train_scaled_bank.shape[1],)),
        tf.keras.layers.Dense(8, activation='relu'),
        tf.keras.layers.Dense(1, activation='sigmoid')
    ]
)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [41]:
model_bank.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model_bank.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 16)             │           160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 305 (1.19 KB)

 Trainable params: 305 (1.19 KB)

 Non-trainable params: 0 (0.00 B)

In [42]:
# Train model
history_model_bank = model_bank.fit(X_train_scaled_bank, y_train_bank, epochs=100, batch_size=32, validation_data=(X_test_scaled_bank, y_test_bank))

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.1250 - loss: 0.8528 - val_accuracy: 0.5000 - val_loss: 0.7280
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step - accuracy: 0.1250 - loss: 0.8442 - val_accuracy: 0.5000 - val_loss: 0.7281
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 185ms/step - accuracy: 0.1250 - loss: 0.8357 - val_accuracy: 0.5000 - val_loss: 0.7280
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step - accuracy: 0.1250 - loss: 0.8276 - val_accuracy: 0.5000 - val_loss: 0.7279
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 168ms/step - accuracy: 0.1250 - loss: 0.8200 - val_accuracy: 0.5000 - val_loss: 0.7277
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 223ms/step - accuracy: 0.1250 - loss: 0.8124 - val_accuracy: 0.5000 - val_loss: 0.7275
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.1250 - loss: 0.8049 - val_accuracy: 0.5000 - val_loss: 0.7274
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step - accuracy: 0.1250 - loss: 0.7975 - val_accuracy: 0.5000 - val_loss: 0.7272
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - accuracy: 0.1250 - loss: 0.7901 - val_accuracy: 0.5000 - val_loss: 0.7271
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - accuracy: 0.1250 - loss: 0.7828 - val_accuracy: 0.5000 - val_loss: 0.7270
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.1250 - loss: 0.7756 - val_accuracy: 0.5000 - val_loss: 0.7270
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.1250 - loss: 0.7684 - val_accuracy: 0.5000 - val_loss: 0.7269
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.1250 - loss: 0.7613 - val_accuracy: 0.5000 - val_loss: 0.7269
Epoch 14/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.2500 - loss: 0.7543 - val_accuracy: 0.5000 - val_loss: 0.7270
Epoch 15/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.2500 - loss: 0.7473 - val_accuracy: 0.5000 - val_loss: 0.7270
Epoch 16/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.2500 - loss: 0.7404 - val_accuracy: 0.5000 - val_loss: 0.7271
Epoch 17/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.2500 - loss: 0.7335 - val_accuracy: 0.5000 - val_loss: 0.7272
Epoch 18/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step - accuracy: 0.2500 - loss: 0.7267 - val_accuracy: 0.5000 - val_loss: 0.7274
Epoch 19/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step - accuracy: 0.2500 - loss: 0.7200 - val_accuracy: 0.5000 - val_loss: 0.7276
Epoch 20/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step - accuracy: 0.2500 - loss: 0.7134 - val_accuracy: 0.5000 - val_loss: 0.7278
Epoch 21/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.3750 - loss: 0.7068 - val_accuracy: 0.5000 - val_loss: 0.7281
Epoch 22/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.3750 - loss: 0.7002 - val_accuracy: 0.5000 - val_loss: 0.7284
Epoch 23/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.3750 - loss: 0.6937 - val_accuracy: 0.5000 - val_loss: 0.7287
Epoch 24/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - accuracy: 0.5000 - loss: 0.6875 - val_accuracy: 0.5000 - val_loss: 0.7290
Epoch 25/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - accuracy: 0.5000 - loss: 0.6812 - val_accuracy: 0.5000 - val_loss: 0.7292
Epoch 26/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.5000 - loss: 0.6748 - val_accuracy: 0.5000 - val_loss: 0.7291
Epoch 27/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.5000 - loss: 0.6685 - val_accuracy: 0.5000 - val_loss: 0.7291
Epoch 28/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.6250 - loss: 0.6621 - val_accuracy: 0.5000 - val_loss: 0.7292
Epoch 29/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step - accuracy: 0.6250 - loss: 0.6556 - val_accuracy: 0.5000 - val_loss: 0.7294
Epoch 30/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - accuracy: 0.6250 - loss: 0.6490 - val_accuracy: 0.5000 - val_loss: 0.7296
Epoch 31/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.6250 - loss: 0.6423 - val_accuracy: 0.5000 - val_loss: 0.7298
Epoch 32/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step - accuracy: 0.6250 - loss: 0.6357 - val_accuracy: 0.5000 - val_loss: 0.7301
Epoch 33/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 0.6250 - loss: 0.6291 - val_accuracy: 0.5000 - val_loss: 0.7305
Epoch 34/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.6250 - loss: 0.6226 - val_accuracy: 0.5000 - val_loss: 0.7309
Epoch 35/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.6250 - loss: 0.6160 - val_accuracy: 0.5000 - val_loss: 0.7313
Epoch 36/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.6250 - loss: 0.6096 - val_accuracy: 0.5000 - val_loss: 0.7317
Epoch 37/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.6250 - loss: 0.6031 - val_accuracy: 0.5000 - val_loss: 0.7322
Epoch 38/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - accuracy: 0.7500 - loss: 0.5967 - val_accuracy: 0.5000 - val_loss: 0.7327
Epoch 39/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.7500 - loss: 0.5905 - val_accuracy: 0.5000 - val_loss: 0.7332
Epoch 40/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.7500 - loss: 0.5845 - val_accuracy: 0.5000 - val_loss: 0.7337
Epoch 41/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.7500 - loss: 0.5785 - val_accuracy: 0.5000 - val_loss: 0.7343
Epoch 42/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 158ms/step - accuracy: 0.7500 - loss: 0.5725 - val_accuracy: 0.5000 - val_loss: 0.7348
Epoch 43/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.7500 - loss: 0.5665 - val_accuracy: 0.5000 - val_loss: 0.7354
Epoch 44/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step - accuracy: 0.7500 - loss: 0.5606 - val_accuracy: 0.5000 - val_loss: 0.7360
Epoch 45/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.7500 - loss: 0.5548 - val_accuracy: 0.5000 - val_loss: 0.7367
Epoch 46/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.7500 - loss: 0.5495 - val_accuracy: 0.5000 - val_loss: 0.7373
Epoch 47/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.7500 - loss: 0.5442 - val_accuracy: 0.5000 - val_loss: 0.7379
Epoch 48/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.7500 - loss: 0.5390 - val_accuracy: 0.5000 - val_loss: 0.7385
Epoch 49/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.7500 - loss: 0.5339 - val_accuracy: 0.5000 - val_loss: 0.7391
Epoch 50/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.7500 - loss: 0.5287 - val_accuracy: 0.5000 - val_loss: 0.7397
Epoch 51/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.7500 - loss: 0.5236 - val_accuracy: 0.5000 - val_loss: 0.7403
Epoch 52/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.7500 - loss: 0.5185 - val_accuracy: 0.5000 - val_loss: 0.7410
Epoch 53/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.7500 - loss: 0.5132 - val_accuracy: 0.5000 - val_loss: 0.7416
Epoch 54/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step - accuracy: 0.7500 - loss: 0.5078 - val_accuracy: 0.5000 - val_loss: 0.7423
Epoch 55/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step - accuracy: 0.7500 - loss: 0.5023 - val_accuracy: 0.5000 - val_loss: 0.7430
Epoch 56/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 0.7500 - loss: 0.4969 - val_accuracy: 0.5000 - val_loss: 0.7437
Epoch 57/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.7500 - loss: 0.4913 - val_accuracy: 0.5000 - val_loss: 0.7446
Epoch 58/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.7500 - loss: 0.4857 - val_accuracy: 0.5000 - val_loss: 0.7455
Epoch 59/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.7500 - loss: 0.4801 - val_accuracy: 0.5000 - val_loss: 0.7466
Epoch 60/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 0.7500 - loss: 0.4745 - val_accuracy: 0.5000 - val_loss: 0.7477
Epoch 61/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - accuracy: 0.7500 - loss: 0.4689 - val_accuracy: 0.5000 - val_loss: 0.7488
Epoch 62/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step - accuracy: 0.7500 - loss: 0.4636 - val_accuracy: 0.5000 - val_loss: 0.7499
Epoch 63/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.7500 - loss: 0.4583 - val_accuracy: 0.5000 - val_loss: 0.7509
Epoch 64/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.8750 - loss: 0.4530 - val_accuracy: 0.5000 - val_loss: 0.7520
Epoch 65/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step - accuracy: 0.8750 - loss: 0.4477 - val_accuracy: 0.5000 - val_loss: 0.7531
Epoch 66/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - accuracy: 0.8750 - loss: 0.4426 - val_accuracy: 0.5000 - val_loss: 0.7541
Epoch 67/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.8750 - loss: 0.4374 - val_accuracy: 0.5000 - val_loss: 0.7552
Epoch 68/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step - accuracy: 0.8750 - loss: 0.4323 - val_accuracy: 0.5000 - val_loss: 0.7562
Epoch 69/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.8750 - loss: 0.4271 - val_accuracy: 0.5000 - val_loss: 0.7572
Epoch 70/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - accuracy: 0.8750 - loss: 0.4220 - val_accuracy: 0.5000 - val_loss: 0.7582
Epoch 71/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.8750 - loss: 0.4170 - val_accuracy: 0.5000 - val_loss: 0.7584
Epoch 72/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.8750 - loss: 0.4121 - val_accuracy: 0.5000 - val_loss: 0.7586
Epoch 73/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - accuracy: 0.8750 - loss: 0.4071 - val_accuracy: 0.5000 - val_loss: 0.7589
Epoch 74/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.8750 - loss: 0.4023 - val_accuracy: 0.5000 - val_loss: 0.7592
Epoch 75/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - accuracy: 0.8750 - loss: 0.3975 - val_accuracy: 0.5000 - val_loss: 0.7602
Epoch 76/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step - accuracy: 0.8750 - loss: 0.3929 - val_accuracy: 0.5000 - val_loss: 0.7613
Epoch 77/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step - accuracy: 0.8750 - loss: 0.3881 - val_accuracy: 0.5000 - val_loss: 0.7625
Epoch 78/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.8750 - loss: 0.3835 - val_accuracy: 0.5000 - val_loss: 0.7636
Epoch 79/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.8750 - loss: 0.3789 - val_accuracy: 0.5000 - val_loss: 0.7647
Epoch 80/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step - accuracy: 0.8750 - loss: 0.3744 - val_accuracy: 0.5000 - val_loss: 0.7659
Epoch 81/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.8750 - loss: 0.3699 - val_accuracy: 0.5000 - val_loss: 0.7670
Epoch 82/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.8750 - loss: 0.3654 - val_accuracy: 0.5000 - val_loss: 0.7683
Epoch 83/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.8750 - loss: 0.3609 - val_accuracy: 0.5000 - val_loss: 0.7697
Epoch 84/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.8750 - loss: 0.3564 - val_accuracy: 0.5000 - val_loss: 0.7711
Epoch 85/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - accuracy: 0.8750 - loss: 0.3520 - val_accuracy: 0.5000 - val_loss: 0.7726
Epoch 86/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.8750 - loss: 0.3476 - val_accuracy: 0.5000 - val_loss: 0.7744
Epoch 87/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.8750 - loss: 0.3432 - val_accuracy: 0.5000 - val_loss: 0.7762
Epoch 88/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.8750 - loss: 0.3389 - val_accuracy: 0.5000 - val_loss: 0.7781
Epoch 89/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step - accuracy: 1.0000 - loss: 0.3345 - val_accuracy: 0.5000 - val_loss: 0.7803
Epoch 90/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - accuracy: 1.0000 - loss: 0.3303 - val_accuracy: 0.5000 - val_loss: 0.7827
Epoch 91/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 1.0000 - loss: 0.3261 - val_accuracy: 0.5000 - val_loss: 0.7855
Epoch 92/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 1.0000 - loss: 0.3224 - val_accuracy: 0.5000 - val_loss: 0.7884
Epoch 93/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step - accuracy: 1.0000 - loss: 0.3190 - val_accuracy: 0.5000 - val_loss: 0.7909
Epoch 94/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - accuracy: 1.0000 - loss: 0.3156 - val_accuracy: 0.5000 - val_loss: 0.7934
Epoch 95/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - accuracy: 1.0000 - loss: 0.3121 - val_accuracy: 0.5000 - val_loss: 0.7959
Epoch 96/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 1.0000 - loss: 0.3087 - val_accuracy: 0.5000 - val_loss: 0.7984
Epoch 97/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step - accuracy: 1.0000 - loss: 0.3053 - val_accuracy: 0.5000 - val_loss: 0.8010
Epoch 98/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step - accuracy: 1.0000 - loss: 0.3020 - val_accuracy: 0.5000 - val_loss: 0.8036
Epoch 99/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 180ms/step - accuracy: 1.0000 - loss: 0.2987 - val_accuracy: 0.5000 - val_loss: 0.8061
Epoch 100/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 202ms/step - accuracy: 1.0000 - loss: 0.2955 - val_accuracy: 0.5000 - val_loss: 0.8085

In [43]:
# Evaluate
loss, accuracy = model_bank.evaluate(X_test_scaled_bank, y_test_bank)
print(f'Test Loss: {loss:.4f}')
print(f'Test Accuracy: {accuracy:.4f}')

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step - accuracy: 0.5000 - loss: 0.8085
Test Loss: 0.8085
Test Accuracy: 0.5000

In [54]:
# Predict new customer
new_customer = pd.DataFrame(
    {
        'CreditScore': [600],
        'Geography': ['France'],
        'Gender': ['Male'],
        'Age': [40],
        'Balance': [62000],
        'NumOfProducts': [1],
        'EstimatedSalary': [55000]

    }
)

# Encode
new_customer['Gender'] = le.transform(new_customer['Gender'])
new_customer = pd.get_dummies(new_customer, columns=['Geography'])

# Add missing dummy columns
for col in [c for c in X_bank.columns if c not in new_customer.columns]:
    new_customer[col] = 0

# Reorder columns
new_customer = new_customer[X_bank.columns]

# Scale
new_customer_scaled = scaler_bank.transform(new_customer)

# Predict
prediction = model_bank.predict(new_customer_scaled)
if prediction[0][0] > 0.5:
    print('Customer will leave')
    print(f'Prediction: {prediction[0][0]:.4f}')
else:
    print('Customer will stay')
    print(f'Prediction: {prediction[0][0]:.4f}')

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step
Customer will stay
Prediction: 0.4217